leaping_animal:
    chance: 0.35
    worlds:
        - world
    entities:
        - ZOMBIE
        - CREEPER

pooping_animal:
    chance: 0.4
    worlds:
        - world
    entities:
        - COW
        - PIG
        - CHICKEN
        - CREEPER

exploding_chicken:
    chance: 0.2
    worlds:
        - world

vampire_pig:
    chance: 0.1
    worlds:
        - world

flying_animal:
    chance: 0.3
    entities:
        - COW
        - PIG
        - CREEPER
        - SKELETON
        - SPIDER
        - ZOMBIE
    worlds:
        - world

random_age:
    chance: 0.15
    worlds:
        - world

meteor:
    chance: 1
    ore_chance: 0.2
    ores:
        - DIAMOND_ORE
        - GOLD_ORE
        - IRON_ORE
        - REDSTONE_ORE
    default: OBSIDIAN
    min_size: 3
    max_size: 6
    worlds:
        - world

disabled:
    - example_action