environments:
    - iceEnvironment
    - waterEnvironment
    - dirtEnvironment
    - netherEnvironment
    - mossyEnvironment
    - sandEnvironment
    - ironEnvironment
    - coalEnvironment
    - goldEnvironment
    - diamondEnvironment
    - redstoneEnvironment
    - diamondEnvironment
    - woodEnvironment
    - webEnvironment
    - foodEnvironment
    - lavaEnvironment
    - airEnvironment

foodEnvironment:
    materials:
        - PUMPKIN
        - MELON_BLOCK
    chance: 0.015

webEnvironment:
    materials:
        - WEB
        - WOOL
    chance: 0.03

diamondEnvironment:
    materials:
        - STONE
        - DIAMOND_ORE
    chance: 0.005

sandEnvironment:
    materials:
        - SANDSTONE
    chance: 0.05

ironEnvironment:
    materials:
        - STONE
        - IRON_ORE
    chance: 0.004

goldEnvironment:
    materials:
        - STONE
        - GOLD_ORE
    chance: 0.0005

redstoneEnvironment:
    materials:
        - STONE
        - REDSTONE_ORE
    chance: 0.01

coalEnvironment:
    materials:
        - STONE
        - COAL_ORE
    chance: 0.01

mossyEnvironment:
    materials:
        - MOSSY_COBBLESTONE
        - COBBLESTONE
    chance: 0.02

woodEnvironment:
    materials:
        - LOG
        - WOOD
    chance: 0.005

iceEnvironment:
    materials:
        - PACKED_ICE
        - ICE
        - GLASS
    chance: 0.06

waterEnvironment:
    materials:
        - STATIONARY_WATER
        - CLAY
    chance: 0.005

dirtEnvironment:
    materials:
        - DIRT
        - SOIL
        - GRASS
    chance: 0.08

netherEnvironment:
    materials:
        - NETHERRACK
        - SOUL_SAND
        - GLOWSTONE
    chance: 0.04

lavaEnvironment:
    materials:
        - STATIONARY_LAVA
        - OBSIDIAN
    chance: 0.03

airEnvironment:
    materials:
        - AIR
    chance: 0.25

startY: 64
minHeight: 2
maxHeight: 8
yVariation: 10
targetWorld: world