environments:
    - iceEnvironment
    - waterEnvironment
    - dirtEnvironment
    - netherEnvironment
    - airEnvironment

iceEnvironment:
    materials:
        - PACKED_ICE
        - ICE
        - GLASS
    chance: 0.06

waterEnvironment:
    materials:
        - WATER
        - CLAY
    chance: 0.01

dirtEnvironment:
    materials:
        - DIRT
        - GRASS
        - BEDROCK
    chance: 0.08

netherEnvironment:
    materials:
        - NETHERRACK
        - SOUL_SAND
        - GLOWSTONE
    chance: 0.04

airEnvironment:
    materials:
        - AIR
    chance: 0.5