leaping_animal:
    chance: 0.35
    worlds:
        - world
    entities:
        - ZOMBIE
        - CREEPER
        - VILLAGER
        - SPIDER

pooping_animal:
    chance: 0.4
    worlds:
        - world
    entities:
        - COW
        - PIG
        - CHICKEN
        - CREEPER
        - VILLAGER

exploding_chicken:
    chance: 0.2
    worlds:
        - world

flying_animal:
    chance: 0.4
    entities:
        - COW
        - PIG
        - CREEPER
        - SKELETON
        - SPIDER
        - ZOMBIE
        - VILLAGER
    worlds:
        - world

mob_column:
    chance: 0.25
    worlds:
        - world
    entities:
        - COW
        - PIG
        - CREEPER
        - SKELETON
        - SPIDER
        - ZOMBIE
        - SQUID
        - CHICKEN
        - HORSE
        - SHEEP
        - VILLAGER
    max_size: 10
    min_size: 3

shooting_entities:
    chance: 0.05
    entities:
        - PIG
        - COW
        - CHICKEN
        - HORSE
        - SHEEP
        - VILLAGER
    worlds:
        - world

flipped_mob:
    chance: 0.4
    entities:
        - CREEPER
        - SKELETON
        - COW
        - PIG
        - SHEEP
        - CHICKEN
        - HORSE
    worlds:
        - world

random_jockeys:
    chance: 0.25
    entities:
        - PIG
        - COW
        - SHEEP
        - WITCH
        - VILLAGER
        - CAVE_SPIDER
        - CHICKEN

mob_names:
    names:
        - Bob
        - Roberto
        - Jack
        - Joe
        - Jill
        - Juan
        - Pablo
        - Mrs.
        - Mr.
        - YOLO
        - Swag
        - Felipe
        - John
        - Alex
        - Eugene
        - Doge
        - Jamie
        - Albert
        - Herobrine

disabled:
    - example_action