leaping_animal:
    chance: 0.35
    worlds:
        - world
    entities:
        - ZOMBIE
        - CREEPER
        - VILLAGER
        - SPIDER

pooping_animal:
    chance: 0.4
    worlds:
        - world
    entities:
        - COW
        - PIG
        - CHICKEN
        - CREEPER
        - VILLAGER

exploding_chicken:
    chance: 0.2
    worlds:
        - world

vampire_pig:
    chance: 0.1
    worlds:
        - world

flying_animal:
    chance: 0.02
    entities:
        - COW
        - PIG
        - CREEPER
        - SKELETON
        - SPIDER
        - ZOMBIE
        - VILLAGER
    worlds:
        - world

random_age:
    chance: 0.5
    worlds:
        - world

meteor:
    chance: 1
    ore_chance: 0.2
    ores:
        - DIAMOND_ORE
        - GOLD_ORE
        - IRON_ORE
        - REDSTONE_ORE
    default: OBSIDIAN
    min_size: 3
    max_size: 6
    worlds:
        - world

mob_column:
    chance: 0.15
    worlds:
        - world
    entities:
        - COW
        - PIG
        - CREEPER
        - SKELETON
        - SPIDER
        - ZOMBIE
        - SQUID
        - CHICKEN
        - HORSE
        - SHEEP
        - VILLAGER
    max_size: 10
    min_size: 3

teleport:
    chance: 0.1
    entities:
        - CREEPER
        - SKELETON
        - SPIDER
        - ZOMBIE
        - SQUID
        - ZOMBIE_PIGMAN
        - CAVE_SPIDER
    max_range: 5
    worlds:
        - world

shooting_entities:
    chance: 0.15
    entities:
        - PIG
        - COW
        - CHICKEN
        - HORSE
        - SHEEP
        - VILLAGER
    worlds:
        - world

flipped_mob:
    chance: 0.1
    entities:
        - CREEPER
        - SKELETON
        - ZOMBIE
        - SPIDER
        - CAVE_SPIDER
        - COW
        - PIG
        - SHEEP
        - CHICKEN
        - HORSE
    worlds:
        - world

random_jockeys:
    chance: 0.05
    entities:
        - PIG
        - COW
        - SHEEP
        - WITCH
        - VILLAGER
        - CAVE_SPIDER
        - CHICKEN

disabled:
    - example_action